project:
  name: quickstart-hitrust-csf
  owner: quickstart-eng@amazon.com
  regions:
    - us-west-2
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
#    - eu-central-1
    - eu-west-1
#    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
  s3_bucket: ''
tests:
  quickstart-hitrust-csf:
    parameters:
      AWSHostedZoneID: Z3AUDQLV95DIKK
      AWSPublicFQDN: $[taskcat_random-string]-hitrust.t.quickstart.awspartner.com
      AvailabilityZones: $[taskcat_genaz_2]
      BastionAccessCidr: 0.0.0.0/0
      BastionKeyPairName: $[taskcat_getkeypair]
      KeyPairName: $[taskcat_getkeypair]
      SSLCertificateARN: ''
      DBPassword: $[taskcat_genpass_8]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      SourceCidr: 0.0.0.0/0
    s3_bucket: ''
    template: templates/main.template